# Generated by Django 3.1.5 on 2021-12-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='password',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user_tb',
            name='username',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
