# Generated by Django 3.1.5 on 2021-12-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_auto_20211227_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
