# Generated by Django 3.1.5 on 2021-12-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_user_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
